apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare-agent-system

resources:
  - ../../base

images:
  - name: ghcr.io/souldest/healthcare-agent-system/backend
    newTag: faff66235bb21019245fe63cbc54ffb6c262f4d9
  - name: ghcr.io/souldest/healthcare-agent-system/frontend
    newTag: faff66235bb21019245fe63cbc54ffb6c262f4d9
