apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare-agent-system

resources:
  - ../../base

images:
  - name: ghcr.io/souldest/healthcare-agent-system/backend
    newTag: 8137ba073465a2c6250d5b9b515a68030c175a3a
  - name: ghcr.io/souldest/healthcare-agent-system/frontend
    newTag: 8137ba073465a2c6250d5b9b515a68030c175a3a
